# Generated by Django 4.1.4 on 2023-06-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0003_ballot_election_delete_historicalballot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='votestatus',
            field=models.IntegerField(choices=[(0, 'Candidacy Phase'), (1, 'Voting Phase'), (2, 'Election Over')], default=0),
        ),
    ]
