# Generated by Django 4.1.4 on 2023-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0004_alter_customuser_votestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='votestatus',
            field=models.IntegerField(choices=[(0, 'Candidacy Phase'), (1, 'Voting Phase'), (2, 'Election Over')], null=True),
        ),
    ]
