# Generated by Django 4.1.4 on 2023-06-18 11:18

import Process.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0006_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Process.managers.CustomUserManager()),
            ],
        ),
    ]
