# Generated by Django 4.1.4 on 2023-06-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalis_within',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical is_within', 'verbose_name_plural': 'historical Is Within'},
        ),
        migrations.AlterModelOptions(
            name='is_within',
            options={'verbose_name_plural': 'Is Within'},
        ),
        migrations.AlterModelOptions(
            name='key_of',
            options={'verbose_name_plural': 'Keys Of'},
        ),
        migrations.AlterModelOptions(
            name='local_center',
            options={'verbose_name_plural': 'Local Centers'},
        ),
        migrations.AlterModelOptions(
            name='regional_center',
            options={'verbose_name_plural': 'Regional Centers'},
        ),
        migrations.AlterField(
            model_name='is_within',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_within', to=settings.AUTH_USER_MODEL),
        ),
    ]
